package cn.uc.yiqibang.dao;


import cn.uc.yiqibang.beans.TComment;
import cn.uc.yiqibang.beans.TNews;
import cn.uc.yiqibang.beans.TNewsExample;
import cn.uc.yiqibang.utils.Result;


import java.util.List;

import org.apache.ibatis.executor.loader.ResultLoader;



public interface TNewsMapper {
    
	Result updateByCondition(TNews news);
	
	Result selectAll();
	
	Result selectAllByPage(int pageNum);
	
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbggenerated Fri Nov 10 16:23:26 CST 2017
     */
//	ɾ������

	 Result deleteByPrimaryKey(Integer id);
	 
	 Result deleteByCondition(TNews news);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbggenerated Fri Nov 10 16:23:26 CST 2017
     */
//	��������
	Result insert(TNews record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbggenerated Fri Nov 10 16:23:26 CST 2017
     */
    Result insertSelective(TNews record);
    
    /**
     * ģ����ѯ
     *
     * @mbggenerated Fri Nov 10 16:23:26 CST 2017
     */
    Result selectByLike(String likeStr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbggenerated Fri Nov 10 16:23:26 CST 2017
     */
    List<TNews> selectByExampleWithBLOBs(TNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbggenerated Fri Nov 10 16:23:26 CST 2017
     */
    List<TNews> selectByExample(TNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbggenerated Fri Nov 10 16:23:26 CST 2017
     */
    Result selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbggenerated Fri Nov 10 16:23:26 CST 2017
     */
    Result updateByPrimaryKeySelective(TNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbggenerated Fri Nov 10 16:23:26 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(TNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbggenerated Fri Nov 10 16:23:26 CST 2017
     */
    int updateByPrimaryKey(TNews record);
    
    Result selectNewsByTypeid(int typeid);
	 

	

    
}