package cn.uc.yiqibang.dao;

import cn.uc.yiqibang.beans.TPic;
import cn.uc.yiqibang.beans.TPicExample;
import cn.uc.yiqibang.utils.Result;

import java.util.List;

public interface TPicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pic
     *
     * @mbggenerated Fri Nov 10 16:23:26 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pic
     *
     * @mbggenerated Fri Nov 10 16:23:26 CST 2017
     */
    int insert(TPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pic
     *
     * @mbggenerated Fri Nov 10 16:23:26 CST 2017
     */
    int insertSelective(TPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pic
     *
     * @mbggenerated Fri Nov 10 16:23:26 CST 2017
     */
    List<TPic> selectByExample(TPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pic
     *
     * @mbggenerated Fri Nov 10 16:23:26 CST 2017
     */
    TPic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pic
     *
     * @mbggenerated Fri Nov 10 16:23:26 CST 2017
     */
    int updateByPrimaryKeySelective(TPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pic
     *
     * @mbggenerated Fri Nov 10 16:23:26 CST 2017
     */
    int updateByPrimaryKey(TPic record);
    
    Result deleteByCondition(TPic pic);
}