package cn.uc.yiqibang.dao;

import cn.uc.yiqibang.beans.TType;
import cn.uc.yiqibang.beans.TUser;
import cn.uc.yiqibang.beans.TUserExample;
import cn.uc.yiqibang.utils.Result;

import java.util.List;

import com.sun.xml.internal.ws.api.pipe.Tube;

public interface TUserMapper {
	
	Result loginUser(TUser user);
	
	Result selectAllByPage(int pageNum); 
    
    Result insertSelective(TUser record);

    Result deleteByPrimaryKey(Integer id);
    
    Result selectAll();
    
    Result updateByPrimaryKeySelective(TUser record);
    
    Result selectByLike(String likeStr);
    
    Result selectByPrimaryKey(Integer id);
	
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Fri Nov 10 16:23:26 CST 2017
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Fri Nov 10 16:23:26 CST 2017
     */
    int insert(TUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Fri Nov 10 16:23:26 CST 2017
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Fri Nov 10 16:23:26 CST 2017
     */
    List<TUser> selectByExample(TUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Fri Nov 10 16:23:26 CST 2017
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Fri Nov 10 16:23:26 CST 2017
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Fri Nov 10 16:23:26 CST 2017
     */
    int updateByPrimaryKey(TUser record);
}